/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './hello-ionic';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/webMethod';
import * as import10 from '../../providers/function';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/infinite-scroll/infinite-scroll-content.ngfactory';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/components/menu/menu-controller';
import * as import30 from 'ionic-angular/components/toolbar/toolbar';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from 'ionic-angular/components/icon/icon';
import * as import37 from 'ionic-angular/components/button/button';
import * as import38 from 'ionic-angular/components/menu/menu-toggle';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import41 from 'ionic-angular/components/navbar/navbar';
import * as import42 from '@angular/common/src/directives/ng_for';
import * as import43 from 'ionic-angular/components/infinite-scroll/infinite-scroll-content';
import * as import44 from 'ionic-angular/components/infinite-scroll/infinite-scroll';
import * as import45 from 'ionic-angular/components/content/content';
import * as import46 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import47 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import48 from 'ionic-angular/components/card/card';
import * as import49 from 'ionic-angular/components/grid/grid';
import * as import50 from '@angular/core/src/security';
export class Wrapper_MainTab2 {
  context:import0.MainTab2;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.MainTab2(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MainTab2_Host:import2.RenderComponentType = (null as any);
class _View_MainTab2_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MainTab2_0_4:Wrapper_MainTab2;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MainTab2_Host0,renderType_MainTab2_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('hello-ionic-page',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MainTab20(this.viewUtils,this.injector(0),this._appEl_0);
    this._MainTab2_0_4 = new Wrapper_MainTab2(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.WebMethod),this.parentInjector.get(import10.GlobalFunction));
    this._appEl_0.initComponent(this._MainTab2_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MainTab2_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MainTab2) && (0 === requestNodeIndex))) { return this._MainTab2_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MainTab2_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MainTab2_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MainTab2_Host === (null as any))) { (renderType_MainTab2_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MainTab2_Host0(viewUtils,parentInjector,declarationEl);
}
export const MainTab2NgFactory:import12.ComponentFactory<import0.MainTab2> = new import12.ComponentFactory<import0.MainTab2>('hello-ionic-page',viewFactory_MainTab2_Host0,import0.MainTab2);
const styles_MainTab2:any[] = ([] as any[]);
var renderType_MainTab2:import2.RenderComponentType = (null as any);
class _View_MainTab20 extends import1.AppView<import0.MainTab2> {
  _el_0:any;
  _Header_0_3:import13.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import14.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import15.Wrapper_Button;
  _MenuToggle_4_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import17.Wrapper_ToolbarItem;
  _query_Button_4_0:import18.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import19.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import20.Wrapper_ToolbarTitle;
  _text_10:any;
  _el_11:any;
  _Icon_11_3:import19.Wrapper_Icon;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Content_16_4:import21.Wrapper_Content;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import22.Wrapper_NgFor;
  _text_20:any;
  _el_21:any;
  _InfiniteScroll_21_3:import23.Wrapper_InfiniteScroll;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _InfiniteScrollContent_23_4:import24.Wrapper_InfiniteScrollContent;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MainTab20,renderType_MainTab2,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import13.Wrapper_Header(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import15.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import29.MenuController),new import26.ElementRef(this._el_4),this.parentInjector.get(import27.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import18.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import19.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Cosplay List (Lastest)\n        ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_11,'name','refresh-circle');
    this.renderer.setElementAttribute(this._el_11,'role','img');
    this._Icon_11_3 = new import19.Wrapper_Icon(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_12
      ]
    )],(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_13
      ]
      )
    ]
    ,(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_16,'padding','');
    this._appEl_16 = new import3.AppElement(16,(null as any),this,this._el_16);
    var compView_16:any = import21.viewFactory_Content0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Content_16_4 = new import21.Wrapper_Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_16.initComponent(this._Content_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_19 = new import3.AppElement(19,16,this,this._anchor_19);
    this._TemplateRef_19_5 = new import34.TemplateRef_(this._appEl_19,viewFactory_MainTab21);
    this._NgFor_19_6 = new import22.Wrapper_NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parentInjector.get(import35.IterableDiffers),this.ref);
    this._text_20 = this.renderer.createText((null as any),'\n\n\n   ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-infinite-scroll',(null as any));
    this._InfiniteScroll_21_3 = new import23.Wrapper_InfiniteScroll(this._Content_16_4.context,this.parentInjector.get(import32.NgZone),new import26.ElementRef(this._el_21));
    this._text_22 = this.renderer.createText(this._el_21,'\n     ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'ion-infinite-scroll-content',(null as any));
    this._appEl_23 = new import3.AppElement(23,21,this,this._el_23);
    var compView_23:any = import24.viewFactory_InfiniteScrollContent0(this.viewUtils,this.injector(23),this._appEl_23);
    this._InfiniteScrollContent_23_4 = new import24.Wrapper_InfiniteScrollContent(this._InfiniteScroll_21_3.context,this.parentInjector.get(import25.Config));
    this._appEl_23.initComponent(this._InfiniteScrollContent_23_4.context,([] as any[]),compView_23);
    compView_23.create(this._InfiniteScrollContent_23_4.context,([] as any[]),(null as any));
    this._text_24 = this.renderer.createText(this._el_21,'\n   ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_16.create(this._Content_16_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_17,
        this._text_18,
        this._appEl_19,
        this._text_20,
        this._el_21,
        this._text_25
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_9,'click',this.eventHandler(this._handle_click_9_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_21,'ionInfinite',this.eventHandler(this._handle_ionInfinite_21_0.bind(this)));
    const subscription_0:any = this._InfiniteScroll_21_3.context.ionInfinite.subscribe(this.eventHandler(this._handle_ionInfinite_21_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import37.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import38.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import39.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import36.Icon) && (11 === requestNodeIndex))) { return this._Icon_11_3.context; }
    if (((token === import40.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import41.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Navbar_2_4.context; }
    if (((token === import30.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Header_0_3.context; }
    if (((token === import34.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import42.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6.context; }
    if (((token === import43.InfiniteScrollContent) && (23 === requestNodeIndex))) { return this._InfiniteScrollContent_23_4.context; }
    if (((token === import44.InfiniteScroll) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._InfiniteScroll_21_3.context; }
    if (((token === import45.Content) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Content_16_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'refresh-circle';
    this._Icon_11_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    if (this._Content_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    const currVal_11:any = this.context.cosplays;
    this._NgFor_19_6.check_ngForOf(currVal_11,throwOnChange,false);
    this._NgFor_19_6.detectChangesInternal(this,this._anchor_19,throwOnChange);
    this._InfiniteScroll_21_3.detectChangesInternal(this,this._el_21,throwOnChange);
    this._InfiniteScrollContent_23_4.detectChangesInternal(this,this._el_23,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._InfiniteScroll_21_3.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this._Icon_11_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_11,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_16_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_16,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_13:any = this._InfiniteScrollContent_23_4.context.inf.state;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_23,'state',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Icon_11_3.context.ngOnDestroy();
    this._InfiniteScroll_21_3.context.ngOnDestroy();
    this._Content_16_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.refresh(this.context)) !== false);
    return (true && pd_0);
  }
  private _handle_ionInfinite_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doInfinite($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_MainTab20(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MainTab2> {
  if ((renderType_MainTab2 === (null as any))) { (renderType_MainTab2 = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_MainTab2,{})); }
  return new _View_MainTab20(viewUtils,parentInjector,declarationEl);
}
class _View_MainTab21 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import46.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  _CardHeader_2_3:import46.Wrapper_CardHeader;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _Row_9_3:import47.Wrapper_Row;
  _text_10:any;
  _el_11:any;
  _Col_11_3:import47.Wrapper_Col;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _Button_13_4:import15.Wrapper_Button;
  _text_14:any;
  _el_15:any;
  _Icon_15_3:import19.Wrapper_Icon;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _Col_19_3:import47.Wrapper_Col;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _Button_21_4:import15.Wrapper_Button;
  _text_22:any;
  _el_23:any;
  _Icon_23_3:import19.Wrapper_Icon;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _Col_27_3:import47.Wrapper_Col;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _Button_29_4:import15.Wrapper_Button;
  _text_30:any;
  _el_31:any;
  _Icon_31_3:import19.Wrapper_Icon;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MainTab21,renderType_MainTab2,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_0,'padding','');
    this._Card_0_3 = new import46.Wrapper_Card(this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card-header',(null as any));
    this._CardHeader_2_3 = new import46.Wrapper_CardHeader(this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n\n      ',(null as any));
    this._text_4 = this.renderer.createText(this._el_2,'\n   ',(null as any));
    this._text_5 = this.renderer.createText(this._el_0,'\n   ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'alt','');
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_0,'\n\n     ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_9,'no-padding','');
    this._Row_9_3 = new import47.Wrapper_Row();
    this._text_10 = this.renderer.createText(this._el_9,'\n       ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'ion-col',(null as any));
    this._Col_11_3 = new import47.Wrapper_Col();
    this._text_12 = this.renderer.createText(this._el_11,'\n         ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'button',(null as any));
    this.renderer.setElementAttribute(this._el_13,'clear','');
    this.renderer.setElementAttribute(this._el_13,'icon-left','');
    this.renderer.setElementAttribute(this._el_13,'ion-button','');
    this.renderer.setElementAttribute(this._el_13,'small','');
    this._appEl_13 = new import3.AppElement(13,11,this,this._el_13);
    var compView_13:any = import15.viewFactory_Button0(this.viewUtils,this.injector(13),this._appEl_13);
    this._Button_13_4 = new import15.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_13),this.renderer);
    this._appEl_13.initComponent(this._Button_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_15,'name','star');
    this.renderer.setElementAttribute(this._el_15,'role','img');
    this._Icon_15_3 = new import19.Wrapper_Icon(this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_15),this.renderer);
    this._text_16 = this.renderer.createText((null as any),'',(null as any));
      compView_13.create(this._Button_13_4.context,[([] as any[]).concat([
        this._text_14,
        this._el_15,
        this._text_16
      ]
    )],(null as any));
    this._text_17 = this.renderer.createText(this._el_11,'\n       ',(null as any));
    this._text_18 = this.renderer.createText(this._el_9,'\n       ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_9,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_19,'text-center','');
    this._Col_19_3 = new import47.Wrapper_Col();
    this._text_20 = this.renderer.createText(this._el_19,'\n         ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'clear','');
    this.renderer.setElementAttribute(this._el_21,'color','default');
    this.renderer.setElementAttribute(this._el_21,'icon-left','');
    this.renderer.setElementAttribute(this._el_21,'ion-button','');
    this.renderer.setElementAttribute(this._el_21,'small','');
    this._appEl_21 = new import3.AppElement(21,19,this,this._el_21);
    var compView_21:any = import15.viewFactory_Button0(this.viewUtils,this.injector(21),this._appEl_21);
    this._Button_21_4 = new import15.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_21),this.renderer);
    this._appEl_21.initComponent(this._Button_21_4.context,([] as any[]),compView_21);
    this._text_22 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_23 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_23,'name','ios-thumbs-up');
    this.renderer.setElementAttribute(this._el_23,'role','img');
    this._Icon_23_3 = new import19.Wrapper_Icon(this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_23),this.renderer);
    this._text_24 = this.renderer.createText((null as any),'',(null as any));
      compView_21.create(this._Button_21_4.context,[([] as any[]).concat([
        this._text_22,
        this._el_23,
        this._text_24
      ]
    )],(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n       ',(null as any));
    this._text_26 = this.renderer.createText(this._el_9,'\n       ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_9,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_27,'text-right','');
    this._Col_27_3 = new import47.Wrapper_Col();
    this._text_28 = this.renderer.createText(this._el_27,'\n         ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'button',(null as any));
    this.renderer.setElementAttribute(this._el_29,'clear','');
    this.renderer.setElementAttribute(this._el_29,'color','default');
    this.renderer.setElementAttribute(this._el_29,'icon-left','');
    this.renderer.setElementAttribute(this._el_29,'ion-button','');
    this.renderer.setElementAttribute(this._el_29,'small','');
    this._appEl_29 = new import3.AppElement(29,27,this,this._el_29);
    var compView_29:any = import15.viewFactory_Button0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Button_29_4 = new import15.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_29),this.renderer);
    this._appEl_29.initComponent(this._Button_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n           ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_31,'name','share-alt');
    this.renderer.setElementAttribute(this._el_31,'role','img');
    this._Icon_31_3 = new import19.Wrapper_Icon(this.parent.parentInjector.get(import25.Config),new import26.ElementRef(this._el_31),this.renderer);
    this._text_32 = this.renderer.createText((null as any),'\n           Download\n         ',(null as any));
      compView_29.create(this._Button_29_4.context,[([] as any[]).concat([
        this._text_30,
        this._el_31,
        this._text_32
      ]
    )],(null as any));
    this._text_33 = this.renderer.createText(this._el_27,'\n       ',(null as any));
    this._text_34 = this.renderer.createText(this._el_9,'\n     ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n   ',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_13,'click',this.eventHandler(this._handle_click_13_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.CardHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._CardHeader_2_3.context; }
    if (((token === import36.Icon) && (15 === requestNodeIndex))) { return this._Icon_15_3.context; }
    if (((token === import37.Button) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._Button_13_4.context; }
    if (((token === import49.Col) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Col_11_3.context; }
    if (((token === import36.Icon) && (23 === requestNodeIndex))) { return this._Icon_23_3.context; }
    if (((token === import37.Button) && ((21 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._Button_21_4.context; }
    if (((token === import49.Col) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Col_19_3.context; }
    if (((token === import36.Icon) && (31 === requestNodeIndex))) { return this._Icon_31_3.context; }
    if (((token === import37.Button) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Button_29_4.context; }
    if (((token === import49.Col) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Col_27_3.context; }
    if (((token === import49.Row) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Row_9_3.context; }
    if (((token === import48.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._CardHeader_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Row_9_3.detectChangesInternal(this,this._el_9,throwOnChange);
    this._Col_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    const currVal_3:any = '';
    this._Button_13_4.check_small(currVal_3,throwOnChange,false);
    const currVal_4:any = '';
    this._Button_13_4.check_clear(currVal_4,throwOnChange,false);
    const currVal_5:any = import4.interpolate(1,'',this.context.$implicit.favoritecss,'');
    this._Button_13_4.check_color(currVal_5,throwOnChange,false);
    if (this._Button_13_4.detectChangesInternal(this,this._el_13,throwOnChange)) { this._appEl_13.componentView.markAsCheckOnce(); }
    const currVal_6:any = 'star';
    this._Icon_15_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Col_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    const currVal_10:any = '';
    this._Button_21_4.check_small(currVal_10,throwOnChange,false);
    const currVal_11:any = '';
    this._Button_21_4.check_clear(currVal_11,throwOnChange,false);
    const currVal_12:any = 'default';
    this._Button_21_4.check_color(currVal_12,throwOnChange,false);
    if (this._Button_21_4.detectChangesInternal(this,this._el_21,throwOnChange)) { this._appEl_21.componentView.markAsCheckOnce(); }
    const currVal_13:any = 'ios-thumbs-up';
    this._Icon_23_3.check_name(currVal_13,throwOnChange,false);
    this._Icon_23_3.detectChangesInternal(this,this._el_23,throwOnChange);
    this._Col_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_17:any = '';
    this._Button_29_4.check_small(currVal_17,throwOnChange,false);
    const currVal_18:any = '';
    this._Button_29_4.check_clear(currVal_18,throwOnChange,false);
    const currVal_19:any = 'default';
    this._Button_29_4.check_color(currVal_19,throwOnChange,false);
    if (this._Button_29_4.detectChangesInternal(this,this._el_29,throwOnChange)) { this._appEl_29.componentView.markAsCheckOnce(); }
    const currVal_20:any = 'share-alt';
    this._Icon_31_3.check_name(currVal_20,throwOnChange,false);
    this._Icon_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_13_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_21_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_29_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.thumbnail_src,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import50.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_7:any = this._Icon_15_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_15,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'\n           Favorite ',this.context.$implicit.favoritecount,'\n         ');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_16,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_14:any = this._Icon_23_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_23,'hide',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = import4.interpolate(1,'\n           Like ',this.context.$implicit.likecount,'\n         ');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_24,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_21:any = this._Icon_31_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_31,'hide',currVal_21);
      this._expr_21 = currVal_21;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_15_3.context.ngOnDestroy();
    this._Icon_23_3.context.ngOnDestroy();
    this._Icon_31_3.context.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.imageclick($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addfavorite($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.addlike($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.shareFb($event,this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_MainTab21(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MainTab21(viewUtils,parentInjector,declarationEl);
}